NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9064-ca-org5.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9064-ca-org5.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9064-ca-org5.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9064-ca-org5.pem
    OrganizationalUnitIdentifier: orderer
