NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8064-ca-org4.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8064-ca-org4.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8064-ca-org4.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8064-ca-org4.pem
    OrganizationalUnitIdentifier: orderer
